### ISSUE TITLE
Should use 45deg

### ISSUE THREAD

**Issue by kunal-mohta** [jshreyans551/frontend-101#3]
https://github.com/jshreyans551/frontend-101/blob/d0eb587a43ef89f78572217f6b370a3622ec1375/A/4.html#L143-L144

For #2 
It looks and works fine, but when working with other developers, it can be really cryptic. This might seem small, but it becomes significant when professionals see your code (e.g. GSoC mentors).
Try to achieve the same effect with the rotation being 45deg

Good work on the task other than this!

**Comment by jshreyans551** [comment]
I'll do the necessary changes
Thanks a lot!

**Comment by kunal-mohta** [comment]
You shouldn't close an issue before getting it reviewed by the person who opened it. :stuck_out_tongue_closed_eyes: 
Such little habits will help you get an upper hand over other developers. :wink:

**Comment by kunal-mohta** [comment]
I saw the latest commit, although the rotation now is 45deg, the cross doesn't look perfect. **You need to keep the appearance perfect and use 45deg.**

**Comment by jshreyans551** [comment]
But I didn't close the issue. Does it close once you commit something referencing the issue?
Yeah I'll look into it again

**Comment by kunal-mohta** [comment]
https://help.github.com/articles/closing-issues-using-keywords/

Cool discovery!! :stuck_out_tongue_winking_eye:

**Comment by jshreyans551** [comment]
Niiice XD
So I tried correcting it by changing the `transform-origin`. Is that the correct way? I don't know if it looks right still.

**Comment by kunal-mohta** [comment]
I think simply increasing the width would do.

**Comment by jshreyans551** [comment]
Yeah that works. Looks better now.
