### ISSUE TITLE
A3 bugs

### ISSUE THREAD

**Issue by kunal-mohta** [jshreyans551/frontend-101#8]
1. Animations go wrong when the window is being resized. (See the gif below)
2. The timing function of the animation doesn't seem to be consistent. It is slow in one cycle, and fast in another. Try to achieve it similar to the video provided in the assignment.
![ezgif-3-730a6142289e](https://user-images.githubusercontent.com/30414954/50146608-26e24580-02da-11e9-9bec-cc64e6022a5c.gif)

**Comment by jshreyans551** [comment]
Bug - I was using the same animation name in all the media queries. That made the animations go haywire as soon as the viewport size crossed the query's boundary line.

**Comment by kunal-mohta** [comment]
Looks fine now!
